### ISSUE TITLE
Default setting for Darkmode?  Or a config to detect a users system setting?

### ISSUE THREAD

**Issue by kartzke** [markteekman/accessible-astro-components#49]
Hi, is there a config or setting that allows an Astro site to use dark mode by default?  Or to detect the mode that the users system is in?

**Comment by markteekman** [comment]
Hey @kartzke! Thanks for submitting the issue 🙂 There currently isn't a config to set the initial state nor does the component check for the users preference. Though, if the user switches modes by using the toggle then that should be honoured on every page load instead of defaulting to the users preference every time (what I think would happen if you'd include that) 🤔 So there needs to be some logic in place to check for that.

That said, it would be a nice addition. I'm sparse on time but I will look into it when I get the change! Any suggestions are welcome of course.
