### ISSUE TITLE
After an accordion-item is opened the fixed height should be removed.

### ISSUE THREAD

**Issue by dasplan** [markteekman/accessible-astro-components#7]
When you open an accordion-item and then you resize the window, things can look weird.
When the slide-open animation ends the fixed height should be removed. Ofcourse you need to reapply the height before closing the item.

**Comment by markteekman** [comment]
Nice find @dasplan! Never noticed that one before, thanks for submitting 😄

**Comment by markteekman** [comment]
@dasplan I went with a function that will recalculate the height of toggled accordion items on window resize instead of removing and reapplying the fixed height (namely because this would then fallback to `height: 0;` which is set in the starting state styles). I've released a patch update with this fix, thanks again for your contribution!
